// core.js — ตัวช่วย, ข้อมูล/สถานะร้าน, session, ธีม, โครงหน้า (header/nav), modal/toast
const $=i=>document.getElementById(i),E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const H=s=>{let h=5381;for(const c of s)h=(h*33^c.charCodeAt(0))>>>0;return h.toString(36)};
const pad=n=>String(n).padStart(2,'0'),ld=d=>d.getFullYear()+'-'+pad(d.getMonth()+1)+'-'+pad(d.getDate()),now=()=>ld(new Date())+' '+pad(new Date().getHours())+':'+pad(new Date().getMinutes());
const D={cfg:{name:'DEXTER STORE',slogan:'ศูนย์รวมไอดีเกมและโค้ดดิจิทัล ส่งอัตโนมัติ 24 ชม.',logo:'',banner:'',banners:[],c1:'#06b6d4',c2:'#6366f1',bg:'#0b0f17',tx:'',topup:1,prof:1,hTop:1,hBuy:1,pay:'PromptPay: 000-000-0000 (ชื่อบัญชี...)',twInfo:'',twPhone:'',qrimg:'',pqOn:1,ptOn:1,pcOn:1,min:10,auto:0,apiUrl:'',pw:H('admin1234')},
cats:[{id:1,name:'ไอดีเกม',img:''},{id:2,name:'เงินในเกม',img:''},{id:3,name:'บัตรเติมเงิน',img:''}],ranks:[{id:1,name:'สมาชิก'},{id:2,name:'VIP'}],users:[],adm:{id:1,name:'admin',bal:0},
prods:[{id:1,name:'Valorant Points 1,000 VP',cat:2,price:300,items:Array.from({length:12},(_,i)=>'VALO-1000VP-'+String(i+1).padStart(3,'0')),img:''},{id:2,name:'ไอดีเกม ตัวอย่าง',cat:1,price:350,items:Array.from({length:4},(_,i)=>'ID-DEMO|PASS-'+String(i+1).padStart(3,'0')),img:''},{id:3,name:'Steam Wallet 500฿',cat:3,price:500,items:Array.from({length:15},(_,i)=>'STEAM-500-'+String(i+1).padStart(3,'0')),img:''}],tx:[],codes:[]};
let S=(()=>{const d=structuredClone(D);let L=null,B=null;try{L=JSON.parse(localStorage.getItem('dx'))}catch(e){}try{B=JSON.parse($('dxdata').textContent)}catch(e){}const j=(L&&(!B||(L.ts||0)>=(B.ts||0)))?L:B;if(j){Object.assign(d,j);d.cfg={...D.cfg,...j.cfg};if(!d.cfg.v2){d.cfg.hTop=d.cfg.hBuy=d.cfg.prof=1;d.cfg.v2=1}if(d.cfg.banner){d.cfg.banners=[...(d.cfg.banners||[]),d.cfg.banner];d.cfg.banner=''}if(j===B&&B.so&&L){d.users=L.users||[];d.tx=L.tx||[];d.codes=L.codes||[];d.adm=L.adm||d.adm}}d.prods.forEach(p=>{if(!Array.isArray(p.items)){p.items=Array.from({length:Math.max(0,p.stock||0)},()=>p.key||'');delete p.stock;delete p.key}});return d})();
const save=()=>{S.ts=Date.now();try{localStorage.setItem('dx',JSON.stringify(S))}catch(e){toast('พื้นที่จัดเก็บเต็ม ลองลดขนาดรูป')}};
let me=null,isAdmin=false,page='home',cat=0,q='',pm='qr',at='ov',F={m:'all',d:''},T={},clk=0,clkT;
let rem=true;const sess=()=>{try{localStorage.removeItem('dx_s');sessionStorage.removeItem('dx_s');if(me&&me!==S.adm)(rem?localStorage:sessionStorage).setItem('dx_s',JSON.stringify({u:me.id}));isAdmin?sessionStorage.setItem('dx_a','1'):sessionStorage.removeItem('dx_a')}catch(e){}};
const logout=()=>{me=null;isAdmin=false;sess();go('home')};
try{const j=JSON.parse(localStorage.getItem('dx_s')||sessionStorage.getItem('dx_s'));rem=!!localStorage.getItem('dx_s');if(j)me=S.users.find(u=>u.id==j.u)||null;isAdmin=sessionStorage.getItem('dx_a')=='1';if(isAdmin)me=S.adm}catch(e){}
let pg0=null;try{pg0=sessionStorage.getItem('dx_p')}catch(e){}if(['home','products','refill','profile','admin'].includes(pg0))page=pg0;if(page=='profile'&&!me)page='home';if(page=='refill'&&!S.cfg.topup)page='home';if(page=='admin'&&!isAdmin)page='home';if(isAdmin&&!pg0)page='admin';
let _u=0;const uid=()=>Date.now()*100+(_u++%100),rb=x=>Math.round(x*100)/100;
let fails=0,lockT=0;const locked=()=>{if(Date.now()<lockT){toast('ลองผิดหลายครั้ง กรุณารอ '+Math.ceil((lockT-Date.now())/1000)+' วินาที');return 1}},bad=m=>{if(++fails>=5){lockT=Date.now()+60000;fails=0}toast(m)};
addEventListener('error',()=>toast('เกิดข้อผิดพลาด กรุณารีเฟรชหน้า'));
addEventListener('storage',e=>{if(e.key!='dx'||!e.newValue)return;try{const j=JSON.parse(e.newValue);Object.assign(S,j);S.cfg={...D.cfg,...j.cfg};if(me)me=me.id==S.adm.id?S.adm:S.users.find(u=>u.id==me.id)||null;if(!/INPUT|SELECT/.test((document.activeElement||{}).tagName||''))render()}catch(x){}});
function fileUI(){document.querySelectorAll('input[type=file]:not(.fu)').forEach(i=>{i.classList.add('fu');const b=document.createElement('div');b.className='fb';b.innerHTML='<span class="btn s"><i class="fa-solid fa-folder-open"></i> เลือกไฟล์</span><span class="m fn">ยังไม่ได้เลือกไฟล์</span>';b.onclick=()=>i.click();i.before(b);i.addEventListener('change',()=>{b.querySelector('.fn').textContent=i.files[0]?i.files[0].name:'ยังไม่ได้เลือกไฟล์'})})}
const toast=m=>{const d=document.createElement('div');d.textContent=m;$('ts').append(d);setTimeout(()=>d.remove(),3000)};
const M=(h,w)=>{$('mo').innerHTML='<div'+(w?` style="max-width:${w}px"`:'')+'>'+h+'</div>';$('mo').classList.remove('hid');fileUI()},CM=()=>$('mo').classList.add('hid');
$('mo').onclick=e=>{if(e.target.id=='mo')CM()};
function imgIn(f,max,cb,t='image/jpeg'){if(!f)return;const r=new FileReader();r.onload=()=>{const i=new Image();i.onload=()=>{const k=Math.min(1,max/Math.max(i.width,i.height)),c=document.createElement('canvas');c.width=i.width*k;c.height=i.height*k;c.getContext('2d').drawImage(i,0,0,c.width,c.height);cb(c.toDataURL(t,.82));toast('อัปโหลดรูปแล้ว')};i.src=r.result};r.readAsDataURL(f)}
const stk=p=>(p.items||[]).length,parseItems=t=>[...new Set(String(t).split(/\r?\n/).map(x=>x.trim()).filter(Boolean))];
const user=id=>S.adm.id==id?S.adm:S.users.find(u=>u.id==id),rk=u=>u===S.adm?'แอดมิน':rank(u.rank),rank=id=>(S.ranks.find(r=>r.id==id)||S.ranks[0]).name,money=n=>Number(n).toLocaleString('th-TH',{minimumFractionDigits:2})+' ฿';
const logo=()=>`<div class="lg">${S.cfg.logo?`<img src="${S.cfg.logo}">`:E(S.cfg.name[0])}</div>`;
const mix=(h,w,k)=>{const n=parseInt(h.slice(1),16);return '#'+[n>>16&255,n>>8&255,n&255].map(v=>Math.round(v+(w-v)*k).toString(16).padStart(2,'0')).join('')};
function theme(){const r=document.documentElement.style,bg=S.cfg.bg||'#0b0f17',n=parseInt(bg.slice(1),16),lt=(.299*(n>>16&255)+.587*(n>>8&255)+.114*(n&255))>150,w=lt?0:255;r.setProperty('--a',S.cfg.c1);r.setProperty('--b',S.cfg.c2);r.setProperty('--bg',bg);r.setProperty('--s',mix(bg,w,lt?.04:.05));r.setProperty('--l',mix(bg,w,lt?.14:.13));const tx=/^#[0-9a-f]{6}$/i.test(S.cfg.tx)?S.cfg.tx:'';r.setProperty('--t',tx||(lt?'#111827':'#e8edf5'));r.setProperty('--m',tx?mix(tx,parseInt(bg.slice(1),16)>0?bg:'#000000',.4):(lt?'#5b6678':'#8a96a8'));document.title=S.cfg.name}
function go(p){if(p=='refill'&&!S.cfg.topup)p='home';page=p;try{sessionStorage.setItem('dx_p',p)}catch(e){}render()}
function render(){theme();const c=S.cfg;let n=[['home','หน้าแรก'],['products','สินค้า']];if(c.topup)n.push(['refill','เติมเงิน']);if(c.prof&&me)n.push(['profile','โปรไฟล์/ประวัติ']);if(isAdmin)n.push(['admin','หลังบ้าน']);
$('hd').innerHTML=`<div class="r" style="cursor:pointer" onclick="lc()">${logo()}<b>${E(c.name)}</b></div><nav>${n.map(x=>`<button class="${page==x[0]?'on':''}" onclick="go('${x[0]}')">${x[1]}</button>`).join('')}</nav><div class="r">${me?`${c.topup?`<span class="a" style="cursor:pointer" onclick="go('refill')"><i class="fa-solid fa-wallet"></i> ${money(me.bal)}</span>`:''}<span>${E(me.name)} <span class="tg">${E(rk(me))}</span></span><button class="btn g s" onclick="logout()">ออกจากระบบ</button>`:`<button class="btn g s" onclick="auth('l')">เข้าสู่ระบบ</button><button class="btn s" onclick="auth('r')">สมัครสมาชิก</button>`}</div>`;
$('ft').textContent='© 2026 '+c.name;$('mn').innerHTML=({home,products:prodPage,refill,profile,admin})[page]();fileUI()}
function lc(){if(page!='home')go('home')}
