// shop.js — หน้าแรก, แบนเนอร์, สินค้า, ซื้อสินค้า, เติมเงิน (ฝั่งลูกค้า)
let bi=0;const bs=()=>{document.querySelectorAll('#bnr img').forEach((m,i)=>m.style.opacity=i==bi?1:0);document.querySelectorAll('#bnr i').forEach((m,i)=>m.className=i==bi?'on':'')};setInterval(()=>{const n=S.cfg.banners.length;if(n>1&&$('bnr')){bi=(bi+1)%n;bs()}},4000);
function home(){const c=S.cfg;if(bi>=c.banners.length)bi=0;return `${c.banners.length?`<div class="bnr" id="bnr">${c.banners.map((b,i)=>`<img src="${b}" style="opacity:${i==bi?1:0}">`).join('')}${c.banners.length>1?`<div class="dots">${c.banners.map((b,i)=>`<i class="${i==bi?'on':''}" onclick="bi=${i};bs()"></i>`).join('')}</div>`:''}</div>`:''}<div class="hero"><h2>${E(c.name)}</h2><p class="m" style="margin:8px 0 16px">${E(c.slogan)}</p><div class="r"><button class="btn" onclick="go('products')">เลือกซื้อสินค้า</button>${c.topup?`<button class="btn g" onclick="go('refill')">เติมเงิน</button>`:''}</div></div><div><h3 style="margin-bottom:10px">สินค้าแนะนำ</h3><div class="grid">${S.prods.slice(0,6).map(pcard).join('')}</div></div>`}
function pcard(p){return `<div class="pc"><div class="pi">${p.img?`<img src="${p.img}">`:'<i class="fa-solid fa-gamepad"></i>'}</div><div class="bd"><b title="${E(p.name)}">${E(p.name)}</b><span class="m">${stk(p)>0?'คงเหลือ '+stk(p):'สินค้าหมด'}</span><div class="r sp"><span class="a"><b>฿${p.price}</b></span><button class="btn s" ${stk(p)>0?'':'disabled style="opacity:.4"'} onclick="buy(${p.id})">ซื้อ</button></div></div></div>`}
const pgH=()=>{const l=S.prods.filter(p=>(!cat||p.cat==cat)&&p.name.toLowerCase().includes(q));return l.map(pcard).join('')||'<span class="m">ไม่พบสินค้า</span>'};
function prodPage(){return `<div class="shop"><div class="cats"><button class="cc ${!cat?'on':''}" onclick="cat=0;render()"><i class="fa-solid fa-border-all"></i>ทั้งหมด</button>${S.cats.map(c=>`<button class="cc ${cat==c.id?'on':''}" onclick="cat=${c.id};render()">${c.img?`<img src="${c.img}">`:'<i class="fa-solid fa-tag"></i>'}${E(c.name)}</button>`).join('')}</div><div style="flex:1;display:grid;gap:12px"><input placeholder="ค้นหาสินค้า..." value="${E(q)}" oninput="q=this.value.toLowerCase();$('pg').innerHTML=pgH()"><div class="grid" id="pg">${pgH()}</div></div></div>`}
function buy(id){if(!me){toast('กรุณาเข้าสู่ระบบก่อน');return auth('l')}const p=S.prods.find(x=>x.id==id);if(stk(p)<1)return toast('สินค้าหมด');if(me.bal<p.price){toast('ยอดเงินไม่พอ');return S.cfg.topup?go('refill'):0}
M(`<b>ยืนยันการสั่งซื้อ</b><div class="st"><div>${E(p.name)}</div><div class="r sp" style="margin-top:6px"><span class="m">ราคา</span><b class="a">${money(p.price)}</b></div><div class="r sp"><span class="m">ยอดคงเหลือหลังซื้อ</span><span>${money(me.bal-p.price)}</span></div></div><div class="r"><button class="btn g" style="flex:1" onclick="CM()">ยกเลิก</button><button class="btn" style="flex:1" onclick="doBuy(${id})">ยืนยันซื้อ</button></div>`)}
function doBuy(id){const p=S.prods.find(x=>x.id==id);if(!me||!p||stk(p)<1||me.bal<p.price){CM();return toast('ไม่สามารถทำรายการได้')}me.bal=rb(me.bal-p.price);const k=p.items.shift();S.tx.unshift({id:uid(),date:now(),user:me.name,type:'buy',title:p.name,amt:-p.price,key:k,st:'ok'});save();M(`<b>ซื้อสำเร็จ</b><span>${E(p.name)}</span><div class="st a" style="word-break:break-all">${E(k)}</div><button class="btn" onclick="CM()">ตกลง</button>`);render()}
function refill(){const c=S.cfg,ms=[['qr','PromptPay','fa-qrcode',c.pqOn],['tw','TrueMoney ซอง','fa-envelope-open-text',c.ptOn],['code','โค้ดเติมเงิน','fa-ticket',c.pcOn]].filter(m=>m[3]);if(!ms.length)return `<div class="card m">ขณะนี้ยังไม่เปิดช่องทางเติมเงิน</div>`;if(!ms.some(m=>m[0]==pm))pm=ms[0][0];return `<div class="card" style="max-width:520px;margin:auto;display:grid;gap:12px"><h3><i class="fa-solid fa-wallet a"></i> เติมเงิน</h3><div class="r">${ms.map(m=>`<button class="btn ${pm==m[0]?'on':'g'}" onclick="pm='${m[0]}';render()"><i class="fa-solid ${m[2]}"></i> ${m[1]}</button>`).join('')}</div>${pm=='code'?`<div><label>กรอกโค้ด</label><input id="rc" placeholder="XXXX-XXXX"></div>`:`<div class="st m">${pm=='qr'?(c.qrimg?`<img src="${c.qrimg}" style="width:180px;display:block;margin:0 auto 8px;border-radius:10px">`:'')+E(c.pay)+'<br>โอนแล้วแนบสลิป แอดมินจะอนุมัติให้':(c.twPhone?'เบอร์รับซอง TrueMoney: <b class="a">'+c.twPhone.replace(/(\d{3})(\d{3})(\d{4})/,'$1-$2-$3')+'</b>':'ยังไม่ได้ตั้งเบอร์รับซอง')+'<br>'+(c.auto&&c.apiUrl?'ใส่ลิงก์ซองอั่งเปา ระบบตรวจและเติมเงินให้อัตโนมัติ':'ส่งลิงก์ซองอั่งเปา แอดมินจะตรวจสอบและอนุมัติ')}</div><div><label>จำนวนเงิน (บาท, ขั้นต่ำ ${c.min})</label><input id="ra" type="number" min="${c.min}"></div>${pm=='qr'?`<div><label>แนบสลิป</label><input type="file" accept="image/*" onchange="imgIn(this.files[0],700,v=>T.slip=v)"></div>`:`<div><label>ลิงก์ซองอั่งเปา</label><input id="rl" placeholder="https://gift.truemoney.com/..."></div>`}`}<button class="btn" onclick="topup()">ยืนยัน</button></div>`}
function topup(){if(!me){toast('กรุณาเข้าสู่ระบบ');return auth('l')}if(pm=='code'){const v=$('rc').value.trim().toUpperCase(),k=S.codes.find(x=>x.code==v&&!x.used);if(!k)return toast('โค้ดไม่ถูกต้องหรือถูกใช้แล้ว');k.used=me.name;me.bal=rb(me.bal+k.amt);S.tx.unshift({id:uid(),date:now(),user:me.name,type:'top',title:'โค้ดเติมเงิน '+v,amt:k.amt,st:'ok'});save();toast('เติมเงินสำเร็จ +'+k.amt);return render()}
if(T.api)return toast('กำลังตรวจสอบรายการก่อนหน้า กรุณารอสักครู่');if(S.tx.filter(x=>x.user==me.name&&x.st=='wait').length>=5)return toast('มีคำขอรออนุมัติครบ 5 รายการแล้ว');const a=rb(parseFloat($('ra').value));if(!(a>=S.cfg.min))return toast('ขั้นต่ำ '+S.cfg.min+' บาท');if(pm=='qr'&&!T.slip)return toast('กรุณาแนบสลิป');let vc='';if(pm=='tw'){const m=$('rl').value.trim().match(/gift\.truemoney\.com\/campaign\/\?v=([0-9A-Za-z]{10,64})/);if(!m)return toast('ลิงก์ซองไม่ถูกต้อง ต้องเป็นลิงก์ gift.truemoney.com');vc=m[1];if(S.tx.some(x=>x.vc==vc))return toast('ซองนี้ถูกส่งเข้ามาแล้ว')}const t={id:uid(),date:now(),user:me.name,type:'top',title:pm=='qr'?'PromptPay':'TrueMoney '+$('rl').value.trim(),amt:a,slip:pm=='qr'?T.slip:'',vc,st:'wait'},c=S.cfg,body={ref:t.id,user:me.name,method:pm,amount:a,slip:t.slip,voucher:pm=='tw'?$('rl').value.trim():'',phone:c.twPhone};T.slip='';S.tx.unshift(t);save();
if(!(c.auto&&c.apiUrl)){toast('ส่งคำขอแล้ว รอแอดมินอนุมัติ');return render()}
T.api=1;toast('กำลังตรวจสอบการชำระเงินอัตโนมัติ...');const ac=new AbortController(),tm=setTimeout(()=>ac.abort(),15000);fetch(c.apiUrl,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal:ac.signal}).then(x=>{if(!x.ok)throw 0;return x.json()}).then(d=>{if(d.success&&d.amount>0){t.amt=rb(+d.amount);t.st='ok';t.slip='';me.bal=rb(me.bal+t.amt);toast('เติมเงินสำเร็จ +'+t.amt)}else if(d.reject){t.st='no';toast(d.message||'การชำระเงินไม่ถูกต้อง')}else toast('รอแอดมินตรวจสอบ')}).catch(()=>toast('เชื่อมต่อระบบตรวจสอบไม่ได้ รอแอดมินอนุมัติ')).finally(()=>{clearTimeout(tm);T.api=0;save();render()})}
